-- require("neotest").setup({
--     adapters = {
--         require("neotest-dotnet")({
--             -- Extra arguments for nvim-dap configuration
--             -- See https://github.com/microsoft/debugpy/wiki/Debug-configuration-settings for values
--             dap = { justMyCode = false },

--             -- Let the test-discovery know about your custom attributes (otherwise tests will not be picked up)
--             -- Note: Only custom attributes for non-parameterized tests should be added here. See the support note about parameterized tests
--             custom_attributes = {
--                 xunit = { "MyCustomFactAttribute" },
--                 nunit = { "MyCustomTestAttribute" },
--                 mstest = { "MyCustomTestMethodAttribute" }
--             },
--             -- Provide any additional "dotnet test" CLI commands here. These will be applied to ALL test runs performed via neotest. These need to be a table of strings, ideally with one key-value pair per item.
--             dotnet_additional_args = {
--                 "--verbosity detailed"
--             },
--             -- Tell neotest-dotnet to use either solution (requires .sln file) or project (requires .csproj or .fsproj file) as project root
--             -- Note: If neovim is opened from the solution root, using the 'project' setting may sometimes find all nested projects, however,
--             --       to locate all test projects in the solution more reliably (if a .sln file is present) then 'solution' is better.
--             discovery_root = "solution" -- Default
--         }),
--         require("neotest-rust") {
--             args = { "--no-capture" },
--             dap_adapter = "lldb",
--         }
--     }
-- })

-- vim.keymap.set('n', '<leader>tr', ':lua require("neotest").run.run()')
-- vim.keymap.set('n', '<leader>tf', ':lua require("neotest").run.run(vim.fn.expand("%"))')
-- vim.keymap.set('n', '<leader>td', ':lua require("neotest").run.run({strategy = "dap"})')
-- vim.keymap.set('n', '<leader>ts', ':lua require("neotest").run.stop()')
-- vim.keymap.set('n', '<leader>ts', ':lua require("neotest").run.stop()')

